name: Playwright Login Test

on:
  push:
    branches: [ main ] # 当推送到主分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  run-playwright-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 建议也将 checkout action 更新到 v4

    - name: Set up Python
      uses: actions/setup-python@v5 # 建议也将 setup-python action 更新到 v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        python -m playwright install --with-deps chromium

    - name: 创建WARP网络
      uses: fscarmen/warp-on-actions@v1.3
      with:
          stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
          mode: client    # Optional. Support [ wireguard, client ]. Default is wireguard.

    - name: Run Playwright script
      run: python playwright_script.py

    - name: Upload screenshot on failure
      if: failure() # 仅在上一步失败时运行
      uses: actions/upload-artifact@v4 # <--- 主要修改在这里，从 v3 更新到 v4
      with:
        name: error-screenshot
        path: error_screenshot.png
